site_name: IDCamPro Documentation
site_author: 'Tobias Däuber'
docs_dir: docs/
repo_name: 'dbnetsoft/IDCamProDocumentation'
repo_url: 'https://github.com/dbnetsoft/IDCamProDocumentation'
nav:
    - Home:
        - Introduction: index.md
        - Installation: home/installation/index.md
   
theme:
    name: "material"
    custom_dir: "overrides"
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - announce.dismiss
    logo: assets/images/logo.png
    palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

copyright: Copyright &copy; 2023 Tobias Däuber, [db]netsoft

extra:
  generator: false

markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - md_in_html

plugins:
  - glightbox